#!/usr/bin/env python
import rospy
import cv2
from cv_bridge import CvBridge
from sensor_msgs.msg import Image

def talker():
    rospy.init_node('webcam_publisher', anonymous=True)
    pub = rospy.Publisher('webcam_image', Image, queue_size=10)
    rate = rospy.Rate(10)  # 10hz
    cap = cv2.VideoCapture(0)
    bridge = CvBridge()

    if not cap.isOpened():
        rospy.logerr("Erro: A câmera não pode ser aberta.")
        return

    try:
        while not rospy.is_shutdown():
            ret, frame = cap.read()
            if not ret:
                rospy.logerr("Erro: Não foi possível capturar o frame.")
                continue

            # Converte a imagem do OpenCV para uma mensagem ROS
            ros_image = bridge.cv2_to_imgmsg(frame, "bgr8")
            pub.publish(ros_image)
            cv2.imshow('Webcam', frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
            rate.sleep()
    finally:
        cap.release()
        cv2.destroyAllWindows()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
